---
title: "EĞİTİMDE ÖLÇME VE DEĞERLENDİRME"
subtitle: "Ders Iceriği"
date: "Bahar - 2025"
output:
  html_document:
  toc: true
  toc_depth: 2
  toc_float: true
theme:  default
highlight: null
css: styles.css
---
```{r include=FALSE}
options(scipen=999)
library(tidyverse)
library(stevemisc)
#library(ggpmisc)
#library(anonymizer)
# library(ggcal)
#library(stringr)
#library(kfigr)
#library(broom)
library(lubridate)
advdate <- function(obj, adv) {
  tmon <- obj + 7*(adv-1)
  # tfri <- obj + 4 + 7*(adv-1)
  tmon <- format(tmon, format="%d/%m")
  # tfri <- format(tfri, format="%d/%m")
  zadv <- sprintf("%02d", adv)
  tmp <- paste("Hafta ",zadv,sep='',", ", tmon)
  return(tmp)
}
mon <- ymd(20250222)

```

------------------------------------------------------------------------
  
|                                        |                                |
|----------------------------------------|--------------------------------|
| **email:** kkatalay\@gmail.com         | **Sinif:** M10             |
| **Ofis saatleri:** Cuma 10:00-12:00    | **Saat:**  14:00           |
| **Ofis:** "Eğitim Bilimleri Bölümü" |                                |
  

 

# Ders Amacı

- Eğitimde ölçme ve değerlendirmenin önemini kavrama
- Ölçme ve değerlendirmeyle ilgili temel kavramlar
- Ölçme araçlarının psikometrik (geçerlik,güvenirlik, kullanışlılık) özellikleri bilgisine sahip olma 
- Başarı testleri geliştirme ve uygulamada yeterli olma.


# Ders Hedefleri

Bu dersi başarıyla tamamlayan öğretmen adayları ders bitiminde aşağıdaki hedeflenen kazanımları edinmiş olur:

**1.** Ölçme ve değerlendirme ile ilgili temel kavramları ve olguları bilir.  


**2.** Ölçme ve değerlendirme dersi ile ilgili kavramları kendi derslerinde kullanır.  

**3.** Hazırlanan bir ölçme aracında olması gereken temel özellikleri sıralar.  

**4.** Psikometrinin güvenirlik ve geçerlik gibi tekniklerinin teorik temellerini anlar.  

**5.** Güvenirlik ve geçerlilik tekniklerini gerçek veri setlerinde uygulayabilir.  

**6.** Eğitimde ölçme ve değerlendirme yapmanın önemini açıklar.  

**7.** Eğitimde kullanılan sonuç ve süreç odaklı ölçme araçlarının özelliklerini bilir ve hazırlar.  


**8.** Test istatistiklerini kullanarak test sonucunda oluşan dağılımları yorumlar.  


**9.** Ölçme ve değerlendirme dersi ile ilgili kavramları kendi derslerinde kullanır.


**10.** Hazırlanan bir ölçme aracında olması gereken temel özellikleri sıralar.  

**11.** Ölçme ve değerlendirme dersi ile ilgili kavramları kendi derslerinde kullanır.  


**12.** Hazırlanan bir ölçme aracında olması gereken temel özellikleri sıralar.   


**13.** Uygulanan ölçme araçlarından alınan öğrenci çıktısını değerlendirir ve öğrenciye not verir.  



# Ders İşlenişi

- Dersler "Ders Planı" başlığı altındaki sıralamaya göre işlenecektir.

- Belirtilen başlık altında her haftanın ilgili ders dokumanına bağlantı moodleda yer almaktadır.

# Notlandırma

-   **50% Ara Sınav**  


-   **50% Genel Sınav** tarihi ve uygulanma şekli daha sonra duyurulacaktır.


# Derse Katılım

- Hacettepe Üniversitesi Ön Lisans, Lisans Eğitim-Öğretim Yönetmeliğinde geçtiği gibi derslere devam zorunludur. 

- Mazeretler de dahil olmak üzere kuramsal (teorik) saatlerin **%30'undan** fazlasına katılmayan öğrenci o dersin genel ve bütünleme sınavına **alınmaz.**


## E-mail ile İletişim

- Bu dökumanda yazmayan her türlü konuda bana `r emo::ji('link')`[katalay@hacettepe.edu.tr](katalay@hacettepe.edu.tr) ile ulaşabilirsiniz.



- Tüm sınıfı ilgilendiren konular için ise ilk derste aranızdan seçtiğimiz gönüllü öğrenci ile iletişim kurulacaktır.


---
## Okuma Listesi

- Atılgan, Hakan. (2007). Eğitimde ölçme ve değerlendirme. Ankara: Anı Yayıncılık.

- Başol, Gülşah. (2007). Eğitimde ölçme ve değerlendirme. İstanbul: Lisans Yayıncılık.

- Baykul, Yaşar & Turgut, M. Fuat. (2010). Eğitimde ölçme ve değerlendirme. Ankara: Pegem Akademi Yayıncılık.

- Baykul, Yaşar. (2010). Eğitim ve psikolojide ölçme. Ankara: Pegem Akademi Yayıncılık.

- Çetin, Bayram (Ed.). (2020). Eğitimde ölçme ve değerlendirme. Ankara: Anı Yayıncılık.

- Demirtaşlı, Nükhet(Ed.). (2017). Eğitimde ölçme ve değerlendirme. Ankara: Anı Yayıncılık.

- Güler, Neşe. (2011). Ölçme ve değerlendirme. Ankara: Pegem Akademi Yayıncılık.

- Özçelik, Durmuş Ali. (2010). Ölçme ve değerlendirme. Ankara: Pegem Akademi Yayıncılık.

- Öztürk Gübeş, N. & Özberk, H. E.(Ed.). (2018). Eğitimde ölçme ve değerlendirme. Ankara: Lisans Yayıncılık.

- Sahin, Murat Doğan(Ed.). (2021). Eğitimde ölçme ve değerlendirme. Ankara: Pegem Akademi Yayıncılık.


- Tan, Şeref. (2009). Öğretimde Ölçme ve değerlendirme. Ankara: Pegem Akademi Yayıncılık.


- Tavşancıl, Ezel (Ed.) (2013). Psikolojik Test ve Değerleme. Ankara. Nobel Yayın Dağıtım Tic.Ltd. Şti.

- Tekin, Halil. (2009). Eğitimde Ölçme ve değerlendirme. Ankara: Yargı Yayınevi

- Turgut, Fuat. (2011). Eğitimde ölçme ve değerlendirme. Ankara: Pegem Akademi Yayıncılık.


# Ders Planı
# `r advdate(mon, 1)`: [Dersin ve Kaynakların Tanınımı](sunum/01_Ders.html)

- Tanışma

- Dersin amacı, içeriği ve kaynaklarının tanıtılması



## Ders Planı

- `r advdate(mon, 2)`:   [Ölçmede Temel Kavramlar](sunum/02_Temel.html)
- `r advdate(mon, 3)`:   [Ölçme araçlarının temel nitelikleri I](sunum/03_Guvenirlik.html)
- `r advdate(mon, 4)`:   [Ölçme araçlarının temel nitelikleri II](sunum/04_Gecerlik.html)
- `r advdate(mon, 5)`:    [Eğitimde kullanılan ölçme araçları I](sunum/05_SINAVLAR1.html) 
- `r advdate(mon, 6)`:   [Eğitimde kullanılan ölçme araçları II](sunum/06_SINAVLAR2.html) 
- `r advdate(mon, 7)`:   Ara Sınav
- `r advdate(mon, 8)`:   [Eğitimde kullanılan ölçme araçları III](sunum/07_SINAVLAR3.html)
- `r advdate(mon, 9)`:   [Eğitimde kullanılan ölçme araçları IV](sunum/08_PERFORMANS.html) 
- `r advdate(mon, 10)`:  [Test Geliştirme](sunum/09_TG.html)
- `r advdate(mon, 11)`:  [Madde Analizi](sunum/10_MADDEIST.html) 
- `r advdate(mon, 12)`:  [Test İstatistikleri](sunum/11_TESTIST.html) 
- `r advdate(mon, 13)`:  [Not Verme ve Genel Tekrar](sunum/14.html) 
- `r advdate(mon, 14)`:  Not Verme ve Genel Tekrar
- `r advdate(mon, 17)`:  Genel Sınav





